FINDINGS = [
 # CRITICAL
 ("G-01","critical","Safety & regulatory","No intended-use statement, regulatory determination, or clinical risk management",
  "The HLD states it “does not by itself establish regulatory compliance” but defines no intended use, no hazard log, and no clinical safety role. Without these, nobody can decide whether Tree A is non-device CDS or Software as a Medical Device.",
  "FDA CDS guidance (FD&C Act §520(o)(1)(E), four non-device criteria); EU MDR Rule 11; IEC 62304 lifecycle; ISO 14971 risk management; UK DCB0129 where applicable.",
  "Write a signed intended-use statement in Sprint 0 and have regulatory counsel make the determination before any real patient data is used. Keep a hazard log where every hazard links to a control and a test ID. Name a clinical safety officer who is not the tree author. Follow an IEC 62304-style process (requirement → test traceability, SOUP register) whatever the determination says. The review screen must let clinicians check the basis of each recommendation for themselves, because that is the fourth non-device criterion."),
 ("G-02","critical","Privacy","“De-identified” telemetry to Arize AX is undefined and, as designed, leaks PHI",
  "Spans will carry <code>observed_at</code>/<code>reported_at</code> and LLM prompts and completions. Under HIPAA Safe Harbor, any date element more specific than the year that relates to the patient is an identifier. Model input and output text also carries PHI by nature. The HLD doesn't name a de-identification method or say whether a BAA with Arize is needed.",
  "HIPAA §164.514(b) (Safe Harbor or Expert Determination); §164.502(e) business associate agreements.",
  "By default, export only structural spans: durations, token counts, status and reason codes, skill and model versions, and IDs hashed with a salt kept inside GCP. Export clinical times as offsets from run start. Don't export prompt or completion content. Content traces are allowed for synthetic data only, or under Expert Determination with a BAA. Enforce this with an attribute allowlist processor and a CI test that injects PHI-shaped values and fails the build. Confirm Vertex AI is covered by the GCP BAA, pin the region, and disable data caching."),
 ("G-03","critical","Safety & regulatory","No kill switch or recall for a defective tree, skill, or model",
  "Rollback “changes the default bundle for new runs” while in-flight runs keep their bundle. If Tree A v0.3 turns out to be clinically wrong, runs already in progress keep producing recommendations, and there's no way to list the patients affected.",
  "Post-market field safety corrective action (ISO 14971 §10, EU MDR Art. 89); standard CDS governance practice.",
  "Give every bundle a status of <code>ACTIVE | SUSPENDED | RETIRED</code>, checked before every run step. <code>SUSPENDED</code> moves in-flight runs to <code>HALTED_SAFETY</code> and shows a banner to clinicians. Add a recall query that lists every run and approved recommendation produced by a bundle version in a date range. Measure suspend-to-halt time in fault tests, with a target under 5 minutes."),
 ("G-04","critical","Audit","The audit trail is mutable and conflates decision audit with access audit",
  "Firestore audit documents can be updated or deleted by any principal with write access, so “every decision can be reconstructed” can't be proven to an auditor. Nothing records who viewed which patient, which is a separate HIPAA requirement.",
  "HIPAA §164.312(b) audit controls; 21 CFR Part 11-style tamper evidence.",
  "Use an append-only audit table: the application role gets INSERT and SELECT only. Hash-chain the events (each stores <code>sha256(prev_hash ∥ payload)</code>), export them hourly to a Cloud Storage bucket with Bucket Lock, and run a daily chain-verification job. Keep a separate PHI access log from application view events plus Cloud Audit Logs Data Access."),
 ("G-05","critical","Reliability","Fail-safe behavior, downtime procedure, and recovery objectives are undefined",
  "You asked for a fault-tolerant system, but the HLD defines no SLO, RPO, RTO, backup or restore process, or what a clinician sees when Vertex AI, P, C, or the platform is down. In a clinical system, a blank or half-rendered screen is itself a hazard.",
  "Clinical downtime procedures (e.g., ONC SAFER Guides: contingency planning); SRE SLO practice.",
  "Fail closed: a partial path is never shown as a recommendation. Unavailability shows an explicit “No recommendation — follow the standard pathway” state. MVP targets: 99.5% API availability during clinical hours, RPO ≤ 5 min (PITR), RTO ≤ 4 h in a single region. The clinical lead owns a written downtime procedure. Hold a timed restore drill before shadow mode."),
 ("G-06","critical","Architecture","Evidence fetched per node lets one path rest on evidence from different times",
  "Architecture step 2 fetches evidence for the current node only. Node 1 might evaluate creatinine at T₀, and node 4 might evaluate at T₀ + 6 h after a review pause, by which time a newer or amended result exists. On resume, the HLD rechecks <em>freshness</em> but not <em>supersession</em>, so a clinician can approve a recommendation that the current record contradicts.",
  "Clinical data currency; the HLD's own “pinned snapshot” principle.",
  "In the MVP, resolve every evidence key the pinned tree references into one snapshot at run start (clinical trees are small). Before creating a recommendation review and again before committing approval, re-check source record versions for all evidence on the path. Any change creates a new snapshot version and recomputes from the earliest affected node. Recommendations carry <code>valid_as_of</code> and <code>expires_at</code>."),
 # HIGH
 ("G-07","high","Safety & regulatory","One clinical expert is the only source of truth and a bottleneck",
  "The same person interprets trees, sets thresholds, labels ground truth, runs twice-weekly case reviews, and approves release. Ground truth from a single labeler has no measured reliability, the approval isn't independent, and four engineers are waiting on one calendar.",
  "Annotation practice (inter-rater agreement); independent verification (IEC 62304 §5.7).",
  "Use at least two annotators on safety-critical eval cases, adjudicate disagreements, and report Cohen's κ. Don't use the set as a release gate until κ ≥ 0.8. Tree author and approver must be different people. Budget clinician time explicitly, about 0.5 FTE across the MVP, and treat it as a tracked dependency."),
 ("G-08","high","Evaluation","Release thresholds are deferred until after the baseline",
  "“Set service targets after Tree A baseline” is reasonable for latency. For safety metrics it invites fitting the gate to the results.",
  "Pre-specified acceptance criteria (clinical evaluation practice; FDA GMLP principle 9).",
  "Sign numeric criteria before the held-out evaluation runs: zero silent false acceptances on the safety suite, and an extraction accuracy target stated as a 95% CI lower bound with a sample-size rationale. For example, 0 errors in 300 cases bounds the true error rate below about 1% (rule of three)."),
 ("G-09","high","Data & interoperability","No clinical data standards: FHIR, LOINC, SNOMED CT, RxNorm, UCUM",
  "Evidence keys like <code>serum_creatinine</code> map to local P/C fields with no bound code system. That's where silent errors come from: a mass-unit and a molar-unit creatinine code treated as the same thing, or a new local code that never matches.",
  "HL7 FHIR R4 / US Core; LOINC; SNOMED CT; RxNorm; UCUM.",
  "Add an evidence concept registry that binds each key to value sets. For example, <code>serum_creatinine</code> → LOINC 2160-0 (mg/dL) and 14682-9 (µmol/L), with a tested UCUM conversion. Adapters emit FHIR Observation-shaped candidates. A code outside the value set becomes <code>unresolved</code> and is never dropped. Version the registry and pin it per run."),
 ("G-10","high","Data & interoperability","Upstream source drift isn't monitored",
  "Labs remap codes, add analyzers, and change reporting units. The adapter then returns “missing” (runs pile up in review) or maps the new data wrongly. Real-world CDS failures often come from exactly this.",
  "Post-deployment monitoring (FDA GMLP principle 10; ONC SAFER).",
  "Profile code, unit, and missing-rate distributions per concept every day against a baseline. Alert on any unmapped code, a unit shift, or a missing-rate change above threshold. Each alert links to a runbook."),
 ("G-11","high","Security","The authorization model is undefined",
  "“Authorized patient/encounter” appears throughout, but the HLD never says who is authorized for which patient, what the reviewer roles are, how break-glass works, or whether engineers can read prod PHI.",
  "HIPAA minimum necessary (§164.502(b)); access control (§164.312(a)).",
  "Sign-in with the organization's IdP over OIDC. Roles: <code>clinical_reviewer</code>, <code>clinical_admin</code>, <code>safety_officer</code>, <code>engineer_readonly</code>. Check patient access against care relationship or unit assignment on every call. Break-glass requires a reason, is time-bound, and alerts the safety officer. No standing engineer access to PHI; elevation is just-in-time and approved."),
 ("G-12","high","Human factors","Mandatory review is the main safety control, and nothing measures it",
  "Without instrumentation, reviews drift into rubber-stamping (automation bias), and nothing in the HLD would detect it.",
  "Human factors engineering (IEC 62366-1); automation-bias literature.",
  "The approve button stays disabled until each flagged evidence item has been opened. Record review dwell time and approval rate. Alert when the rolling approval rate or median dwell time crosses thresholds agreed with the clinical lead. Run usability sessions with at least three clinicians before shadow mode."),
 ("G-13","high","Architecture","Two stores, Firestore and Cloud SQL, create the consistency problem the HLD then works around",
  "Cloud SQL exists only for ADK session history, which forces a cross-store recovery protocol. Extraction calls are single-shot and bounded, so they don't need durable conversational sessions. Firestore also makes an append-only audit trail and recall queries harder than they need to be.",
  "Transactional outbox pattern; operational simplicity for small teams.",
  "<strong>Proposed ADR — needs your sign-off, because HLD §12 lists this as confirmed.</strong> Use one Cloud SQL for PostgreSQL store for run state, snapshot metadata, outbox, and audit. Run ADK with an ephemeral session per operation and persist only the validated result, keyed by <code>operation_id</code>. You get row constraints, <code>REVOKE UPDATE</code> on audit, and SQL recall queries. Revisit only if write volume demands it."),
 ("G-14","high","Security","The security architecture stops at IAM and Secret Manager",
  "The HLD has no environment separation, VPC Service Controls, CMEK, private connectivity to P/C, threat model, SBOM or dependency provenance, or deploy attestation.",
  "NIST SP 800-53 / HITRUST control families; IEC 62304 SOUP management; SLSA.",
  "Separate dev, staging, and prod projects, with PHI only in prod. Put Cloud SQL, Cloud Storage, and Vertex AI inside a VPC-SC perimeter, and use CMEK. Read P and C in BigQuery only through authorized views, across VPC-SC perimeters. Build a STRIDE threat model that includes document prompt injection. CI uses Workload Identity Federation, produces an SBOM, and deploys through Binary Authorization."),
 ("G-15","high","Safety & regulatory","Tree content has no governed lifecycle",
  "Trees are “published after clinical approval”, but there's no author/approver separation, no guideline citation per node, and no review expiry. Clinical guidelines change, and a tree approved in 2026 can quietly become wrong.",
  "Clinical content governance (CDS knowledge management practice).",
  "Each tree version records its clinical owner, an approver who is not the author, a guideline reference on every decision node, and a <code>review_by</code> date (default 12 months). A tree past its <code>review_by</code> date can't start new runs."),
 # MEDIUM
 ("G-16","medium","Architecture","The run state machine is incomplete",
  "There's no state for a review nobody actions, a safety halt, or supersession, and no transition table. Nothing prevents two active runs for the same patient and tree, and the idempotency key has no scope or TTL.",
  "Explicit state machines for safety-relevant workflows.",
  "Add <code>EXPIRED</code> and <code>HALTED_SAFETY</code>, plus a transition table enforced in code and tested exhaustively. Allow one active run per (patient, encounter, tree). Give idempotency keys a 24 h TTL and scope them per user."),
 ("G-17","medium","Architecture","Leases, fencing tokens, outbox, and sweeper overlap for an MVP",
  "Spokes are read-only, so executing a step twice wastes compute but can't corrupt state, provided the commit is conditional on the expected revision. The lease layer adds failure modes without adding safety.",
  "Optimistic concurrency control; YAGNI.",
  "In the MVP, use a Postgres job queue (<code>FOR UPDATE SKIP LOCKED</code>) and commit with <code>UPDATE … WHERE revision = :expected</code>. Transition, audit event and next job go in one transaction. Drop leases, fencing tokens and Cloud Tasks. Move to outbox plus Cloud Tasks only when scale or isolation demands it."),
 ("G-18","medium","Scope","Explanation and reconciliation agents add clinical risk to the MVP for little value",
  "An LLM explanation that has to pass grounding checks, and an LLM that proposes resolutions to conflicts, are both hard to validate. Neither is needed to prove the pipeline.",
  "Minimize risk surface in first release.",
  "In the MVP, explanations come from deterministic templates approved by the clinical lead, and every conflict goes to clinician review. Defer both agents until the extraction eval gates are proven."),
 ("G-19","medium","Consistency","The architecture diagram contradicts the text",
  "Adapters and ADK spokes point straight at the snapshot, bypassing the hub that “controls all dispatch”. The snapshot validator is mentioned in the caption but not drawn. The explanation agent is missing.",
  "Document consistency.",
  "Replaced by the amended diagram below: all reads go through the hub, and the validator and executor are explicit stages."),
 ("G-20","medium","Data & interoperability","Clinical time zones aren't specified",
  "HL7 v2 and many lab feeds send local timestamps without an offset. Freshness math on naïve times is off by hours around DST changes, which matters at a 24 h boundary.",
  "ISO 8601 with offset; HL7 v2 TS/DTM.",
  "Adapters resolve naïve timestamps using each source's configured zone. If no zone is configured, the timestamp is <code>unresolved</code>. Test both DST transitions at the freshness boundary. Display times in facility local time with a zone label."),
 ("G-21","medium","Evaluation","Model retirement and the meaning of “replay” aren't addressed",
  "Pinning a Vertex model doesn't stop its scheduled retirement. “Replay reproduces the path” holds for the executor but can't hold for LLM re-extraction, and the HLD doesn't separate the two.",
  "Model lifecycle management; audit reproducibility.",
  "Track retirement dates in a model registry, with an alert and a re-validation ticket 90 days before retirement. Define replay as re-executing over the <em>stored</em> snapshot, which must match exactly. Re-extraction is a new evaluation and is never used as audit proof."),
 ("G-22","medium","Delivery","No lead role, Engineer 4 overloaded, and no quality ownership",
  "Engineer 4 owns GCP, ADK wiring, checkpoint/outbox, review API, review UI, and instrumentation. Nobody owns architecture decisions, safety evidence, fault testing, or the release gate.",
  "Team topology; two-person review for safety-critical code.",
  "The lead owns ADRs, the hazard log, the threat model, the fault-injection suite, and go/no-go. Instrumentation moves to Engineer 2, and the review UI moves to Engineer 3 once the executor is stable. Executor, validator, and authz code need two approvals (CODEOWNERS)."),
 ("G-23","medium","Rollout","“Shadow runs” have no evaluation protocol",
  "Shadow mode is listed as a rollout stage, but the HLD doesn't say what shadow output is compared against, who adjudicates, or what result lets the team proceed to pilot.",
  "Silent-mode clinical AI evaluation practice.",
  "Hide shadow output from clinical users behind a feature flag. The clinical lead adjudicates a weekly sample against the documented clinical decision. Define the concordance measure and exit criterion before shadow mode starts. Classify every discordance as source, extraction, policy, tree, or workflow."),
]

